export const dummyData = {
  username: "owner",
  streak: 0,
  _version: 11,
  level: 0,
  badges: {
    BadgeQuestion50: true,
    BadgeQuestion100: false,
    BadgeQuestion200: true,
    BadgeDayHalf: false,
    BadgeDayMonth: true,
    BadgeDayThreeMonths: false,
    BadgeHappy40: true,
    BadgeSad40: false,
    BadgeFear40: true,
    BadgeDisgust40: false,
    BadgeSurprise40: true,
    BadgeAngry40: false,
    BadgeHappy60: true,
    BadgeSad60: false,
    BadgeFear60: true,
    BadgeDisgust60: false,
    BadgeSurprise60: true,
    BadgeAngry60: false,
  },
  SpeakingQuestions: {
    Happy: 0.7,
    Sad: 0.2,
    Angry: 0.4,
    Fear: 0.3,
    Disgust: 0.5,
    Surprise: 0.6,
  },
  ListeningQuestions: {
    Happy: 0.7,
    Sad: 0.2,
    Angry: 0.4,
    Fear: 0.3,
    Disgust: 0.5,
    Surprise: 0.6,
  },
  CoversationQuestions: {
    Happy: 0.7,
    Sad: 0.2,
    Angry: 0.4,
    Fear: 0.3,
    Disgust: 0.5,
    Surprise: 0.6,
  },
  HasOnboarded: false,
  SpeakingAccuracy: {
    Happy: 0.7,
    Sad: 0.2,
    Angry: 0.4,
    Fear: 0.3,
    Disgust: 0.5,
    Surprise: 0.6,
  },
  ListeningAccuracy: {
    Happy: 0.7,
    Sad: 0.2,
    Angry: 0.4,
    Fear: 0.3,
    Disgust: 0.5,
    Surprise: 0.6,
  },
  ConversationAccuracy: {
    Happy: 0.7,
    Sad: 0.2,
    Angry: 0.4,
    Fear: 0.3,
    Disgust: 0.5,
    Surprise: 0.6,
  },
};
