export const dummyData = {
  id: 1,
  username: "john123",
  password: "password123",
  streak: "5 days",
  level: 3,
  badges: {
    badge50qs: true,
    // badge100qs: false,
    badge200qs:true,
    badgedayhalf:false,
    badgedaymonth:true,
    badgedaythreemonths:false,
  },
  speakingQuestion: {
    happy: 9,
    sad: 5,
    angry: 2,
    fear:9,
    disgust: 10,
    surprise: 8,
  },
  listeningQuestion: {
    happy: 9,
    sad: 5,
    angry: 2,
    fear:9,
    disgust: 10,
    surprise: 8,
  },
  conversationQuestion: {
    happy: 9,
    sad: 5,
    angry: 2,
    fear:9,
    disgust: 10,
    surprise: 8,
  },

  hasOnboarded: true,

  speakingAccuracy: {
    happy: 0.09,
    sad: 0.5,
    angry: 0.2,
    fear: 0.1,
    disgust: 0.1,
    surprise: 0.08,
  },
  listeningAccuracy: {
    happy: 0.09,
    sad: 0.5,
    angry: 0.2,
    fear: 0.1,
    disgust: 0.1,
    surprise: 0.08,
  },
  conversationAccuracy: {
      happy: 0.09,
      sad: 0.5,
      angry: 0.2,
      fear: 0.1,
      disgust: 0.1,
      surprise: 0.08,
  },
};