export const userData = {
    username: "jojo_user_1",
    streak: 0,
    level: 1,
    badges: {
      BadgeQuestion50: false,
      BadgeQuestion100: false,
      BadgeQuestion200: false,
      BadgeDayHalf: false,
      BadgeDayMonth: false,
      BadgeDayThreeMonths: false,
      BadgeHappy40: false,
      BadgeSad40: false,
      BadgeFear40: false,
      BadgeDisgust40: false,
      BadgeSurprise40: false,
      BadgeAngry40: false,
      BadgeHappy60: false,
      BadgeSad60: false,
      BadgeFear60: false,
      BadgeDisgust60: false,
      BadgeSurprise60: false,
      BadgeAngry60: false,
    },
    SpeakingQuestions: {
      Happy: 0.0,
      Sad: 0.0,
      Angry: 0.0,
      Fear: 0.0,
      Disgust: 0.0,
      Surprise: 0.0,
    },
    ListeningQuestions: {
      Happy: 0.0,
      Sad: 0.0,
      Angry: 0.0,
      Fear: 0.0,
      Disgust: 0.0,
      Surprise: 0.0,
    },
    CoversationQuestions: {
      Happy: 0.0,
      Sad: 0.0,
      Angry: 0.0,
      Fear: 0.0,
      Disgust: 0.0,
      Surprise: 0.0,
    },
    HasOnboarded: false,
    SpeakingAccuracy: {
      Happy: 0.0,
      Sad: 0.0,
      Angry: 0.0,
      Fear: 0.0,
      Disgust: 0.0,
      Surprise: 0.0,
    },
    ListeningAccuracy: {
      Happy: 0.0,
      Sad: 0.0,
      Angry: 0.0,
      Fear: 0.0,
      Disgust: 0.0,
      Surprise: 0.0,
    },
    ConversationAccuracy: {
      Happy: 0.0,
      Sad: 0.0,
      Angry: 0.0,
      Fear: 0.0,
      Disgust: 0.0,
      Surprise: 0.0,
    },
  };